version: 2

models:
  - name: stg_customers
    description: "Cleaned and standardized customer data from bronze layer"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer email (lowercase, trimmed)"
        tests:
          - not_null
      - name: name
        description: "Customer name"
        tests:
          - not_null
      - name: segment
        description: "Customer segment (enterprise, mid-market, smb)"
      - name: region
        description: "Customer region"
      - name: created_at
        description: "Customer creation timestamp"
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned and standardized order data from bronze layer"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: status
        description: "Normalized order status"
        tests:
          - not_null
          - accepted_values:
              values: ['completed', 'pending', 'cancelled', 'failed', 'unknown']
      - name: total_amount
        description: "Order total amount (decimal)"
        tests:
          - not_null
      - name: created_at
        description: "Order creation timestamp"
        tests:
          - not_null

  - name: stg_products
    description: "Cleaned and standardized product data from bronze layer"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: name
        description: "Product name"
        tests:
          - not_null
      - name: category
        description: "Standardized product category"
        tests:
          - not_null
          - accepted_values:
              values: ['Electronics', 'Clothing', 'Home & Garden', 'Sports & Outdoors', 'Books', 'Other']
      - name: price
        description: "Product price (decimal)"
        tests:
          - not_null
      - name: created_at
        description: "Product creation timestamp"
        tests:
          - not_null

  - name: stg_order_items
    description: "Cleaned and standardized order line items from bronze layer"
    columns:
      - name: order_item_id
        description: "Unique order item identifier"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to orders"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        description: "Foreign key to products"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        description: "Quantity ordered (must be > 0)"
        tests:
          - not_null
      - name: price
        description: "Unit price at time of order"
        tests:
          - not_null
      - name: line_total
        description: "Calculated line total (quantity * price)"
        tests:
          - not_null
      - name: created_at
        description: "Order item creation timestamp"
        tests:
          - not_null
