"""JavaScript security function generator for Cube.

T057: Generate cube.js checkAuth function
T058: Generate cube.js queryRewrite function
T059: Add filter configuration environment variables

This module generates JavaScript code for Cube's security functions:
- checkAuth: Validates JWT tokens and extracts security context
- queryRewrite: Adds row-level security filters to queries

Functional Requirements:
- FR-030: Generate checkAuth function with JWT validation
- FR-031: Generate queryRewrite function with filter injection
- FR-032: Support configurable claim mappings
- FR-033: Generate filter environment variables

Architecture:
    Generated JavaScript is injected into cube.js configuration.
    JWT validation uses Cube's built-in @cubejs-backend/jwt package.
    Row-level filters are applied via SECURITY_CONTEXT.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger(__name__)


class CubeSecurityGenerator:
    """Generator for Cube security functions.

    Generates JavaScript code for checkAuth and queryRewrite functions
    based on ConsumptionConfig security settings.

    Attributes:
        config: Security configuration dictionary

    Example:
        >>> config = {
        ...     "row_level": True,
        ...     "user_id_claim": "sub",
        ...     "roles_claim": "roles",
        ...     "filter_claims": ["organization_id"],
        ... }
        >>> generator = CubeSecurityGenerator(config)
        >>> js_code = generator.generate_check_auth()
        >>> "checkAuth" in js_code
        True
    """

    def __init__(self, config: dict[str, Any]) -> None:
        """Initialize the security generator.

        Args:
            config: Security configuration from ConsumptionConfig
        """
        self.config = config
        self._log = logger.bind(
            row_level=config.get("row_level", False),
        )

    def generate_check_auth(self) -> str:
        """Generate checkAuth function for JWT validation (T057).

        Returns:
            JavaScript function code for checkAuth

        Example:
            >>> generator = CubeSecurityGenerator({"row_level": True})
            >>> code = generator.generate_check_auth()
            >>> "async function checkAuth" in code
            True
        """
        if not self.config.get("row_level", False):
            return self._generate_no_auth()

        user_id_claim = self.config.get("user_id_claim", "sub")
        roles_claim = self.config.get("roles_claim", "roles")
        filter_claims = self.config.get("filter_claims", [])

        # Build filter claims extraction
        filter_extractions = []
        for claim in filter_claims:
            # Sanitize claim name for JavaScript variable
            safe_name = self._sanitize_js_name(claim)
            filter_extractions.append(
                f"    const {safe_name} = claims['{claim}'];"
            )

        # Build security context object
        context_entries = [f"      user_id: claims['{user_id_claim}']"]
        context_entries.append(f"      roles: claims['{roles_claim}'] || []")

        for claim in filter_claims:
            safe_name = self._sanitize_js_name(claim)
            context_entries.append(f"      {claim}: {safe_name}")

        lines = [
            "// checkAuth function generated by floe-cube",
            "// Validates JWT and extracts security context",
            "async function checkAuth(req, authorization) {",
            "  // JWT validation delegated to Cube's built-in middleware",
            "  const claims = authorization;",
            "",
            f"  // Extract user ID from '{user_id_claim}' claim",
            f"  const userId = claims['{user_id_claim}'];",
            "  if (!userId) {",
            "    throw new Error('Unauthorized: missing user identifier');",
            "  }",
            "",
            f"  // Extract roles from '{roles_claim}' claim",
            f"  const roles = claims['{roles_claim}'] || [];",
        ]

        # Add filter claim extractions
        if filter_extractions:
            lines.append("")
            lines.append("  // Extract filter claims for row-level security")
            lines.extend(filter_extractions)

        # Build security context
        lines.extend([
            "",
            "  // Return security context for query filtering",
            "  return {",
            "    securityContext: {",
        ])

        for entry in context_entries:
            lines.append(entry + ",")

        lines.extend([
            "    }",
            "  };",
            "}",
        ])

        self._log.info("check_auth_generated", claims_count=len(filter_claims))
        return "\n".join(lines)

    def generate_query_rewrite(self) -> str:
        """Generate queryRewrite function for row-level filtering (T058).

        Returns:
            JavaScript function code for queryRewrite

        Example:
            >>> generator = CubeSecurityGenerator({
            ...     "row_level": True,
            ...     "filter_claims": ["organization_id"],
            ... })
            >>> code = generator.generate_query_rewrite()
            >>> "queryRewrite" in code
            True
        """
        if not self.config.get("row_level", False):
            return self._generate_passthrough_rewrite()

        filter_claims = self.config.get("filter_claims", [])

        lines = [
            "// queryRewrite function generated by floe-cube",
            "// Injects row-level security filters into queries",
            "function queryRewrite(query, { securityContext }) {",
            "  if (!securityContext) {",
            "    throw new Error('Unauthorized: no security context');",
            "  }",
        ]

        # Add filter conditions based on claims
        if filter_claims:
            lines.extend([
                "",
                "  // Add row-level security filters",
                "  const filters = [];",
            ])

            for claim in filter_claims:
                safe_name = self._sanitize_js_name(claim)
                lines.extend([
                    "",
                    f"  // Filter by {claim} if present in security context",
                    f"  if (securityContext.{claim}) {{",
                    "    filters.push({",
                    f"      member: `${{query.cube}}.{claim}`,",
                    "      operator: 'equals',",
                    f"      values: [securityContext.{claim}],",
                    "    });",
                    "  }",
                ])

            lines.extend([
                "",
                "  // Merge filters with existing query filters",
                "  return {",
                "    ...query,",
                "    filters: [...(query.filters || []), ...filters],",
                "  };",
            ])
        else:
            lines.extend([
                "",
                "  // No filter claims configured - pass query through",
                "  return query;",
            ])

        lines.append("}")

        self._log.info("query_rewrite_generated", filter_count=len(filter_claims))
        return "\n".join(lines)

    def generate_env_vars(self) -> dict[str, str]:
        """Generate filter configuration environment variables (T059).

        Returns:
            Dictionary of environment variable name to value

        Example:
            >>> generator = CubeSecurityGenerator({
            ...     "row_level": True,
            ...     "filter_claims": ["organization_id"],
            ... })
            >>> env_vars = generator.generate_env_vars()
            >>> "FLOE_SECURITY_FILTER_CLAIMS" in env_vars
            True
        """
        env_vars: dict[str, str] = {}

        if not self.config.get("row_level", False):
            env_vars["FLOE_SECURITY_ENABLED"] = "false"
            return env_vars

        env_vars["FLOE_SECURITY_ENABLED"] = "true"
        env_vars["FLOE_SECURITY_USER_ID_CLAIM"] = self.config.get("user_id_claim", "sub")
        env_vars["FLOE_SECURITY_ROLES_CLAIM"] = self.config.get("roles_claim", "roles")

        filter_claims = self.config.get("filter_claims", [])
        if filter_claims:
            env_vars["FLOE_SECURITY_FILTER_CLAIMS"] = ",".join(filter_claims)

        jwt_secret_ref = self.config.get("jwt_secret_ref")
        if jwt_secret_ref:
            # Use K8s secret reference syntax
            env_vars["CUBEJS_JWT_SECRET"] = f"${{{jwt_secret_ref}}}"

        jwt_audience = self.config.get("jwt_audience")
        if jwt_audience:
            env_vars["CUBEJS_JWT_AUDIENCE"] = jwt_audience

        jwt_issuer = self.config.get("jwt_issuer")
        if jwt_issuer:
            env_vars["CUBEJS_JWT_ISSUER"] = jwt_issuer

        self._log.info("env_vars_generated", count=len(env_vars))
        return env_vars

    def generate_full_config(self) -> str:
        """Generate complete cube.js security configuration.

        Returns:
            JavaScript module content with checkAuth and queryRewrite

        Example:
            >>> generator = CubeSecurityGenerator({"row_level": True})
            >>> config = generator.generate_full_config()
            >>> "module.exports" in config
            True
        """
        check_auth = self.generate_check_auth()
        query_rewrite = self.generate_query_rewrite()

        lines = [
            "// Cube security configuration generated by floe-cube",
            "// DO NOT EDIT - this file is auto-generated",
            "",
            check_auth,
            "",
            query_rewrite,
            "",
            "module.exports = {",
            "  checkAuth,",
            "  queryRewrite,",
            "};",
            "",
        ]

        return "\n".join(lines)

    def write_security_config(self, output_dir: Path) -> Path:
        """Write security configuration to file.

        Args:
            output_dir: Directory to write security.js to

        Returns:
            Path to the written file
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        security_file = output_dir / "security.js"
        content = self.generate_full_config()
        security_file.write_text(content)

        self._log.info("security_config_written", path=str(security_file))
        return security_file

    def _generate_no_auth(self) -> str:
        """Generate passthrough checkAuth when security is disabled."""
        return """// checkAuth function - security disabled
async function checkAuth(req, authorization) {
  // Row-level security is disabled
  // All requests are allowed without authentication
  return {};
}"""

    def _generate_passthrough_rewrite(self) -> str:
        """Generate passthrough queryRewrite when security is disabled."""
        return """// queryRewrite function - security disabled
function queryRewrite(query, context) {
  // Row-level security is disabled
  // Queries pass through unmodified
  return query;
}"""

    def _sanitize_js_name(self, name: str) -> str:
        """Sanitize string for use as JavaScript variable name.

        Args:
            name: Original name

        Returns:
            JavaScript-safe variable name
        """
        # Replace non-alphanumeric with underscore
        safe = "".join(c if c.isalnum() else "_" for c in name)
        # Ensure doesn't start with digit
        if safe and safe[0].isdigit():
            safe = "_" + safe
        return safe or "_unnamed"
