version: 2

sources:
  - name: bronze
    description: |
      Bronze layer tables created by Dagster Python assets.
      These tables are written to the Polaris catalog in the 'demo' namespace.
    database: polaris_catalog
    schema: demo
    tables:
      - name: raw_customers
        description: Raw customer data loaded to Iceberg

      - name: raw_products
        description: Raw product data loaded to Iceberg

      - name: raw_orders
        description: Raw order data loaded to Iceberg

      - name: raw_order_items
        description: Raw order item data loaded to Iceberg
