"""Profile writer for serializing profiles to YAML files.

T033: [US2] Implement ProfileWriter with YAML serialization
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


class ProfileWriter:
    """Write dbt profile configurations to YAML files.

    Handles serialization of profile dictionaries to profiles.yml format,
    including creating parent directories and adding header comments.

    The writer always overwrites existing files (FR-005) since profiles.yml
    is a generated artifact, not user-managed.

    Example:
        >>> writer = ProfileWriter()
        >>> writer.write(profile, Path(".floe/profiles/profiles.yml"))
    """

    # Header comment for generated files
    HEADER_COMMENT = """\
# Auto-generated by floe-dbt - DO NOT EDIT MANUALLY
# This file is overwritten on each compilation.
# To customize, modify floe.yaml and recompile.

"""

    def write(self, profile: dict[str, Any], path: Path) -> None:
        """Write profile dictionary to YAML file.

        Creates parent directories if they don't exist.
        Overwrites existing file (profiles.yml is generated, not managed).

        Args:
            profile: Profile dictionary to serialize.
            path: Output file path.
        """
        # Create parent directories if needed
        path.parent.mkdir(parents=True, exist_ok=True)

        # Generate YAML content
        yaml_content = self.to_yaml_string(profile)

        # Write with header comment
        path.write_text(self.HEADER_COMMENT + yaml_content)

    def to_yaml_string(self, profile: dict[str, Any]) -> str:
        """Serialize profile dictionary to YAML string.

        Uses safe YAML dump with sensible formatting options.

        Args:
            profile: Profile dictionary to serialize.

        Returns:
            YAML-formatted string.
        """
        return yaml.safe_dump(
            profile,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=120,
        )
