# Flux HelmRelease for floe-runtime
#
# Deploy with: kubectl apply -f helmrelease.yaml
#
# Prerequisites:
#   - Flux v2 installed in the cluster
#   - GitRepository or HelmRepository source configured
#   - Destination namespace created
#
# Covers: 007-FR-004 (GitOps deployment with Flux)
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: floe-runtime
  namespace: floe
spec:
  interval: 5m
  timeout: 10m

  chart:
    spec:
      chart: ./charts/floe-runtime
      sourceRef:
        kind: GitRepository
        name: floe-project
        namespace: flux-system
      interval: 1m

  # Environment-specific values
  valuesFrom:
    - kind: ConfigMap
      name: floe-runtime-values
      valuesKey: values.yaml
      optional: false

  # Inline value overrides
  values:
    global:
      labels:
        app.kubernetes.io/managed-by: flux

    floe-dagster:
      enabled: true
      floe:
        compiledArtifacts:
          enabled: true

    floe-cube:
      enabled: true

  # Upgrade configuration
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
    cleanupOnFail: true
    crds: CreateReplace

  # Install configuration
  install:
    remediation:
      retries: 3
    crds: Create

  # Test configuration
  test:
    enable: false
    ignoreFailures: false

  # Rollback configuration
  rollback:
    timeout: 5m
    cleanupOnFail: true

  # Drift detection
  driftDetection:
    mode: enabled
    ignore:
      # Ignore HPA-managed replicas
      - paths:
          - /spec/replicas
        target:
          kind: Deployment

---
# GitRepository source for floe-runtime
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: floe-project
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-org/floe-project
  ref:
    branch: main
  secretRef:
    name: github-credentials  # Optional: for private repos
