name: 'floe_demo'
version: '1.0.0'
config-version: 2

# dbt project for floe-runtime demo
# Implements Silver → Gold transformation layers for medallion architecture

profile: 'floe_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "SELECT COUNT(*) FROM duckdb_secrets()"

models:
  floe_demo:
    # Staging models (Bronze → Silver)
    # Cleaning, deduplication, type casting
    staging:
      +materialized: view
      +schema: silver
      +tags: ["staging", "silver"]

    # Intermediate models (Silver business logic)
    # Joins, calculations, enrichment
    intermediate:
      +materialized: view
      +schema: silver
      +tags: ["intermediate", "silver"]

    # Marts (Silver → Gold)
    # Aggregated, analytics-ready datasets
    marts:
      +materialized: table
      +schema: gold
      +tags: ["marts", "gold"]

# Data quality tests
tests:
  +store_failures: true
  +schema: test_results

# Seeds configuration
seeds:
  floe_demo:
    +schema: seeds
