version: 2

models:
  - name: mart_customer_orders
    description: "Gold mart: Customer order analytics for BI tools"
    meta:
      owner: "data_team"
      classification: "internal"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: order_total
        description: "Total order amount"
        tests:
          - not_null
      - name: has_amount_mismatch
        description: "Data quality flag for amount discrepancies"

  - name: mart_revenue
    description: "Gold mart: Daily revenue analytics by region, status, and segment"
    meta:
      owner: "data_team"
      classification: "internal"
    columns:
      - name: revenue_date
        description: "Revenue date (daily grain)"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue for the period"
        tests:
          - not_null
      - name: order_count
        description: "Number of orders"
        tests:
          - not_null

  - name: mart_product_performance
    description: "Gold mart: Product sales performance by category"
    meta:
      owner: "data_team"
      classification: "internal"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: total_revenue
        description: "Total revenue from product sales"
        tests:
          - not_null
      - name: total_units_sold
        description: "Total units sold"
        tests:
          - not_null
