# Floe Demo Mart Models Schema
#
# Defines models, columns, and semantic metadata for mart layer.
# These models feed into Cube semantic layer for consumption.
#
# Covers: 007-FR-029 (E2E validation tests)
# Covers: 007-FR-031 (Medallion architecture - Gold layer)

version: 2

models:
  - name: mart_revenue
    description: "Daily revenue aggregation for business analytics"
    meta:
      floe:
        layer: gold
        domain: finance
        owner: analytics-team
    columns:
      - name: order_date
        description: "Date of orders"
        tests:
          - not_null
      - name: total_orders
        description: "Total number of orders placed"
      - name: completed_orders
        description: "Number of successfully completed orders"
      - name: gross_revenue
        description: "Total revenue from completed orders"
      - name: avg_order_value
        description: "Average order value for completed orders"
      - name: total_units_sold
        description: "Total product units sold"
      - name: unique_products_sold
        description: "Count of distinct products sold"
      - name: unique_customers
        description: "Count of distinct customers who placed orders"

  - name: mart_customer_segments
    description: "Customer segmentation based on purchase behavior"
    meta:
      floe:
        layer: gold
        domain: marketing
        owner: growth-team
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: customer_segment
        description: "Segment classification (vip, loyal, active, new, never_ordered)"
        tests:
          - accepted_values:
              values: ['vip', 'loyal', 'active', 'new', 'never_ordered']
      - name: churn_risk
        description: "Churn risk level (high, medium, low, unknown)"
        tests:
          - accepted_values:
              values: ['high', 'medium', 'low', 'unknown']
      - name: total_revenue
        description: "Lifetime revenue from this customer"
      - name: avg_order_value
        description: "Customer's average order value"
      - name: total_orders
        description: "Lifetime order count"
      - name: days_since_last_order
        description: "Days since customer's last order"

  - name: mart_product_analytics
    description: "Product performance analytics and rankings"
    meta:
      floe:
        layer: gold
        domain: product
        owner: product-team
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Product display name"
      - name: category
        description: "Product category"
      - name: total_revenue
        description: "Total revenue generated by product"
      - name: total_units_sold
        description: "Total units sold"
      - name: revenue_rank
        description: "Product ranking by revenue (1 = highest)"
      - name: performance_tier
        description: "Performance classification tier"
        tests:
          - accepted_values:
              values: ['top_performer', 'good_performer', 'average', 'underperformer', 'no_sales']
      - name: price_variance_pct
        description: "Percentage variance between average selling price and current price"

# Semantic layer metrics (for documentation - Cube consumes these models)
metrics:
  - name: total_revenue
    label: "Total Revenue"
    description: "Sum of gross revenue from completed orders"
    type: sum
    sql: "gross_revenue"
    model: ref('mart_revenue')
    timestamp: order_date
    time_grains: [day, week, month, quarter, year]

  - name: average_order_value
    label: "Average Order Value"
    description: "Mean revenue per completed order"
    type: average
    sql: "avg_order_value"
    model: ref('mart_revenue')
    timestamp: order_date
    time_grains: [day, week, month, quarter, year]

  - name: customer_count
    label: "Customer Count"
    description: "Count of unique customers"
    type: count_distinct
    sql: "customer_id"
    model: ref('mart_customer_segments')

  - name: vip_customer_count
    label: "VIP Customers"
    description: "Count of VIP segment customers"
    type: count
    sql: "customer_id"
    model: ref('mart_customer_segments')
    filters:
      - field: customer_segment
        operator: "="
        value: "'vip'"

exposures:
  - name: cube_orders
    label: "Cube Orders Semantic Layer"
    description: "Orders data exposed via Cube REST/GraphQL/SQL APIs"
    type: application
    maturity: high
    url: "http://cube:4000"
    owner:
      name: Analytics Team
      email: analytics@example.com
    depends_on:
      - ref('mart_revenue')
      - ref('mart_customer_segments')

  - name: cube_products
    label: "Cube Products Semantic Layer"
    description: "Product analytics exposed via Cube APIs"
    type: application
    maturity: high
    url: "http://cube:4000"
    owner:
      name: Product Team
      email: product@example.com
    depends_on:
      - ref('mart_product_analytics')
